[2025-06-27T04:38:28.658+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T04:38:28.705+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark manual__2025-06-27T04:33:19.078517+00:00 [queued]>
[2025-06-27T04:38:28.713+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark manual__2025-06-27T04:33:19.078517+00:00 [queued]>
[2025-06-27T04:38:28.713+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-27T04:38:28.762+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Structure_Data_With_Spark> on 2025-06-27 04:33:19.078517+00:00
[2025-06-27T04:38:28.767+0000] {standard_task_runner.py:64} INFO - Started process 343 to run task
[2025-06-27T04:38:28.771+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_processing_pipeline', 'Structure_Data_With_Spark', 'manual__2025-06-27T04:33:19.078517+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpt8n0kirz']
[2025-06-27T04:38:28.773+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask Structure_Data_With_Spark
[2025-06-27T04:38:29.065+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark manual__2025-06-27T04:33:19.078517+00:00 [running]> on host 3b2681f5d151
[2025-06-27T04:38:29.364+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_processing_pipeline' AIRFLOW_CTX_TASK_ID='Structure_Data_With_Spark' AIRFLOW_CTX_EXECUTION_DATE='2025-06-27T04:33:19.078517+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-27T04:33:19.078517+00:00'
[2025-06-27T04:38:29.366+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T04:38:29.410+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-06-27T04:38:29.411+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --conf spark.yarn.jars=hdfs://namenode:9000/user/spark/jars/* --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation
[2025-06-27T04:38:29.479+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-06-27T04:38:29.480+0000] {spark_submit.py:571} INFO - JAVA_HOME is not set
[2025-06-27T04:38:29.480+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T04:38:29.507+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --conf spark.yarn.jars=hdfs://namenode:9000/user/spark/jars/* --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation. Error code is: 1.
[2025-06-27T04:38:29.511+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_processing_pipeline, task_id=Structure_Data_With_Spark, run_id=manual__2025-06-27T04:33:19.078517+00:00, execution_date=20250627T043319, start_date=20250627T043828, end_date=20250627T043829
[2025-06-27T04:38:29.633+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task Structure_Data_With_Spark (Cannot execute: spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --conf spark.yarn.jars=hdfs://namenode:9000/user/spark/jars/* --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation. Error code is: 1.; 343)
[2025-06-27T04:38:29.666+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-27T04:38:29.703+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T04:38:30.060+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
