[2025-06-27T04:33:26.093+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T04:33:26.135+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark scheduled__2025-06-26T00:08:00+00:00 [queued]>
[2025-06-27T04:33:26.142+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark scheduled__2025-06-26T00:08:00+00:00 [queued]>
[2025-06-27T04:33:26.142+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T04:33:26.188+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Structure_Data_With_Spark> on 2025-06-26 00:08:00+00:00
[2025-06-27T04:33:26.192+0000] {standard_task_runner.py:64} INFO - Started process 214 to run task
[2025-06-27T04:33:26.195+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_processing_pipeline', 'Structure_Data_With_Spark', 'scheduled__2025-06-26T00:08:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpab40xjbk']
[2025-06-27T04:33:26.197+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask Structure_Data_With_Spark
[2025-06-27T04:33:26.727+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark scheduled__2025-06-26T00:08:00+00:00 [running]> on host 3b2681f5d151
[2025-06-27T04:33:27.440+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_processing_pipeline' AIRFLOW_CTX_TASK_ID='Structure_Data_With_Spark' AIRFLOW_CTX_EXECUTION_DATE='2025-06-26T00:08:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-26T00:08:00+00:00'
[2025-06-27T04:33:27.441+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T04:33:27.479+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-06-27T04:33:27.480+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation
[2025-06-27T04:33:27.570+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-06-27T04:33:27.571+0000] {spark_submit.py:571} INFO - JAVA_HOME is not set
[2025-06-27T04:33:27.572+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T04:33:27.603+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation. Error code is: 1.
[2025-06-27T04:33:27.610+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_processing_pipeline, task_id=Structure_Data_With_Spark, run_id=scheduled__2025-06-26T00:08:00+00:00, execution_date=20250626T000800, start_date=20250627T043326, end_date=20250627T043327
[2025-06-27T04:33:27.645+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task Structure_Data_With_Spark (Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation. Error code is: 1.; 214)
[2025-06-27T04:33:27.652+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-27T04:33:27.699+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T04:33:27.701+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-27T06:50:55.862+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T06:50:55.932+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark scheduled__2025-06-26T00:08:00+00:00 [queued]>
[2025-06-27T06:50:55.948+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark scheduled__2025-06-26T00:08:00+00:00 [queued]>
[2025-06-27T06:50:55.949+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T06:50:55.986+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Structure_Data_With_Spark> on 2025-06-26 00:08:00+00:00
[2025-06-27T06:50:56.002+0000] {standard_task_runner.py:64} INFO - Started process 267 to run task
[2025-06-27T06:50:56.015+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_processing_pipeline', 'Structure_Data_With_Spark', 'scheduled__2025-06-26T00:08:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp8ca3zq4u']
[2025-06-27T06:50:56.024+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask Structure_Data_With_Spark
[2025-06-27T06:50:56.127+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-27T06:50:56.249+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark scheduled__2025-06-26T00:08:00+00:00 [running]> on host 7037b04ca3e2
[2025-06-27T06:50:56.536+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_processing_pipeline' AIRFLOW_CTX_TASK_ID='Structure_Data_With_Spark' AIRFLOW_CTX_EXECUTION_DATE='2025-06-26T00:08:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-26T00:08:00+00:00'
[2025-06-27T06:50:56.538+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T06:50:56.610+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-06-27T06:50:56.612+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation
[2025-06-27T06:50:58.892+0000] {spark_submit.py:571} INFO - Using properties file: null
[2025-06-27T06:50:59.048+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-06-27T06:50:59.049+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2025-06-27T06:50:59.050+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2025-06-27T06:50:59.051+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2025-06-27T06:50:59.052+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2025-06-27T06:50:59.052+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2025-06-27T06:50:59.053+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2025-06-27T06:50:59.053+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2025-06-27T06:50:59.054+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2025-06-27T06:50:59.055+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2025-06-27T06:50:59.056+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-06-27T06:50:59.088+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T06:50:59.130+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation. Error code is: 1.
[2025-06-27T06:50:59.859+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_processing_pipeline, task_id=Structure_Data_With_Spark, run_id=scheduled__2025-06-26T00:08:00+00:00, execution_date=20250626T000800, start_date=20250627T065055, end_date=20250627T065059
[2025-06-27T06:50:59.887+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task Structure_Data_With_Spark (Cannot execute: /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation. Error code is: 1.; 267)
[2025-06-27T06:50:59.924+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-27T06:50:59.981+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T06:50:59.985+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
